const CONFIG = {
    titleWeb: "Web này tạo ra để gửi cho chị 😗",
    introTitle: 'He sờ lô chị ',
    introDesc: `Nay rảnh nên gửi tặng chị cái này😆`,
    btnIntro: 'Zô nhận quà nè 😙',
    title: 'Hôm nay ngày 20/10, chúc chị nhiều sức khoẻ  luôn xinh đẹp và thành công trong công việc nhé😊',
    desc: 'Không biết chị có thích tà tữa không em tặng chị 1 ly size L nhá😆',
    btnYes: 'Không ,chị không thích trà sữa 😐',
    btnNo: 'ok chốt 2 ly em nhé😊',
    question: 'Sao thế chê trà sữa em tặng à😐🤣',
    btnReply: 'Không ,ko sửa được đâu nhá 😆😆😆',
    reply: 'ok:)',
    mess: 'thôi viết vội chị ạ',
    messDesc: 'Tới giờ làm rồi ,zô chốt đơn đi chị 😊',
    btnAccept: 'ok e',
    messLink: 'https://dvmobifone.com/mng2/get-data.html '}
