const CONFIG = {
    titleWeb: "Web này tạo ra để gửi cho em Bích 😗",
    introTitle: 'He sờ lô Bích ',
    introDesc: `Nay rảnh nên gửi tặng em cái này😆`,
    btnIntro: 'Zô nhận quà nè 😙',
    title: 'Hôm nay ngày 20/10, anh chúc bé bích luôn xinh đẹp và thành công trong công việc cố lấy mốc 45tr em nhé😊',
    desc: 'Không biết em có thích tà tữa không anh tặng em 1 ly size L nhá😆',
    btnYes: 'Không ,em không thích trà sữa 😐',
    btnNo: 'Dạ có 2 ly anh nhé😊',
    question: 'Sao thế chê trà sữa anh tặng à😐🤣',
    btnReply: 'Không ạ ,ko sửa được đâu nhá 😆😆😆',
    reply: 'Dạ 😐',
    mess: 'Lớn rồi bớt chơi game tập trung vào công việc đi em nhé😁',
    messDesc: 'Tới giờ làm rồi ,zô chốt đơn đi e😊',
    btnAccept: 'Dạ😐',
    messLink: 'https://dvmobifone.com/mng2/get-data.html'}
